YodaCodingForumBack/Models/UserInfo.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace YodaCodingForumBack.Models
{
    public partial class UserInfo
    {
        public UserInfo()
        {
            Chatrooms = new HashSet<Chatroom>();
            CollectClasses = new HashSet<CollectClass>();
            ReceiveMessages = new HashSet<ReceiveMessage>();
            Reports = new HashSet<Report>();
            SendMessages = new HashSet<SendMessage>();
            UserBlocks = new HashSet<UserBlock>();
            UserCollects = new HashSet<UserCollect>();
            UserFollowers = new HashSet<UserFollower>();
            UserFollows = new HashSet<UserFollow>();
            UserImages = new HashSet<UserImage>();
            UserLikeComments = new HashSet<UserLikeComment>();
            UserLikes = new HashSet<UserLike>();
            UserNotices = new HashSet<UserNotice>();
            UserPoints = new HashSet<UserPoint>();
        }

        public string UserId { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public string UserName { get; set; }
        public string UserNickname { get; set; }
        public string UserSax { get; set; }
        public DateTime? UserBirthday { get; set; }
        public string UserAddress { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public string UserExperience { get; set; }
        public string UserProfession { get; set; }
        public string UserStatus { get; set; }
        public string Remark { get; set; }
        public DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public DateTime LastupdateDate { get; set; }
        public string LastupdateUser { get; set; }
        public int Version { get; set; }

        public virtual ICollection<Chatroom> Chatrooms { get; set; }
        public virtual ICollection<CollectClass> CollectClasses { get; set; }
        public virtual ICollection<ReceiveMessage> ReceiveMessages { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<SendMessage> SendMessages { get; set; }
        public virtual ICollection<UserBlock> UserBlocks { get; set; }
        public virtual ICollection<UserCollect> UserCollects { get; set; }
        public virtual ICollection<UserFollower> UserFollowers { get; set; }
        public virtual ICollection<UserFollow> UserFollows { get; set; }
        public virtual ICollection<UserImage> UserImages { get; set; }
        public virtual ICollection<UserLikeComment> UserLikeComments { get; set; }
        public virtual ICollection<UserLike> UserLikes { get; set; }
        public virtual ICollection<UserNotice> UserNotices { get; set; }
        public virtual ICollection<UserPoint> UserPoints { get; set; }
    }
}

YodaCodingForumBack/Controllers/UserInfoController.cs
using YodaCodingForumBack.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace YodaCodingForumBack.Controllers
{
    public class UserInfoController : Controller
    {
        private readonly ArticleDBContext _context;
        public UserInfoController(ArticleDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var userQuery = (from u in _context.UserInfos
                             join p in _context.UserPoints on u.UserId equals p.UserId
                             orderby u.UserStatus descending, u.CreateDate descending
                             select new UserInfoList
                             {
                                 uid = u.UserId,
                                 account = u.UserAccount,
                                 name = u.UserName,
                                 status = u.UserStatus,
                                 sex = u.UserSax,
                                 email = u.UserEmail,
                                 point = p.PointAmount,
                                 creatdate = u.CreateDate
                             }).ToList();


            var userVM = new SearchClass
            {
                userList = listcheckdata(userQuery)
            };
            return View(userVM);
        }

        public IActionResult Search(string searchString)
        {
            var userQuery = from u in _context.UserInfos
                            join p in _context.UserPoints on u.UserId equals p.UserId
                            orderby u.UserStatus descending, u.CreateDate descending
                            select new UserInfoList
                            {
                                uid = u.UserId,
                                account = u.UserAccount,
                                name = u.UserName,
                                status = u.UserStatus,
                                sex = u.UserSax,
                                email = u.UserEmail,
                                point = p.PointAmount,
                                creatdate = u.CreateDate
                            };

            if (!String.IsNullOrEmpty(searchString))
            {
                userQuery = userQuery.Where(t => t.account.Contains(searchString.Replace(" ","")));
            }

            var userVM = new SearchClass
            {
                userList = listcheckdata(userQuery.ToList())
            };
            return View(userVM);
        }

        public IActionResult UserList(string uid)
        {

            var uinfoQuery = (from u in _context.UserInfos
                              join p in _context.UserPoints on u.UserId equals p.UserId
                              where u.UserId == uid
                              select new UserInfoClass
                              {
                                  uid = u.UserId,
                                  account = u.UserAccount,
                                  name = u.UserName,
                                  nickname = u.UserNickname,
                                  sax = u.UserSax,
                                  birthday = u.UserBirthday.ToString(),
                                  address = u.UserAddress,
                                  email = u.UserEmail,
                                  phone = u.UserPhone,
                                  experience = u.UserExperience,
                                  profession = u.UserProfession,
                                  status = u.UserStatus,
                                  point = p.PointAmount,
                                  remark = u.Remark,
                                  create_date = u.CreateDate,
                                  create_user = u.CreateUser,
                                  lastupdate_date = u.LastupdateDate,
                                  lastupdate_user = u.LastupdateUser,
                                  version = u.Version
                              }).ToList();

            var user = new SearchClass
            {
                userInfo = checkdata(uinfoQuery)
            };
            return View(user);
        }

        [HttpPost]
        public ActionResult UserList(string uid, string status, string remark)
        {
            var userStatusUpdate = _context.UserInfos.Find(uid);
            userStatusUpdate.UserStatus = status;
            userStatusUpdate.Remark = remark;
            userStatusUpdate.LastupdateDate = DateTime.Now;
            userStatusUpdate.LastupdateUser = "SYS";
            userStatusUpdate.Version++;
            _context.SaveChanges();

            return Redirect($"/UserInfo/UserList?uid={uid}");

        }

        //傳入會員List資料
        public List<UserInfoList> listcheckdata(List<UserInfoList> userList)
        {
            //顯示
            foreach (var u in userList)
            {
                u.status = u.status == "N" ? "未認證" : (u.status == "T" ? "正常" : "關閉");
                u.sex = u.sex == "N" ? "不提供" : (u.sex == "M" ? "男" : "女");
            }
            return userList;
        }

        //傳入會員頁面的資料
        public List<UserInfoClass> checkdata(List<UserInfoClass> userinfo)
        {
            foreach (var u in userinfo)
            {
                //使用者圖片
                var imageQuery = from chk in _context.UserImages
                                 where chk.UserId == u.uid
                                 select chk;

                //如使用者沒有設定圖片
                if (imageQuery.Count() == 0)
                {
                    //則依照性別顯示系統設定圖片
                    var sysimageQuery = from img in _context.UserImages
                                        where img.UserId == "SYS"
                                        where img.ImageId == "Defult" + u.sax
                                        select img;

                    foreach (var img in sysimageQuery)
                    {
                        u.uimage = img.Uimage;
                    }
                }
                //顯示使用者設定圖片
                else
                {
                    foreach (var img in imageQuery)
                    {
                        u.uimage = img.Uimage;
                    }
                }

                //顯示用
                u.nickname = u.nickname == null ? "未提供" : u.nickname;
                u.birthday = u.birthday == null ? "未提供" : u.birthday;
                u.address = u.address == null ? "未提供" : u.address;
                u.phone = u.phone == null ? "未提供" : u.phone;
                u.experience = u.experience == null ? "未提供" : u.experience;
                u.profession = u.profession == null ? "未提供" : u.profession;
                u.sax = u.sax == "N" ? "不提供" : (u.sax == "M" ? "男" : "女");


            }
            return userinfo;
        }
    }
}

YodaCodingForumBack/Views/UserInfo/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor hca
@model YodaCodingForumBack.Models.SearchClass
@{
    ViewData["Title"] = "會員管理";
}

<style>

    .pagination {
        margin: 0;
    }

        .pagination li:hover {
            cursor: pointer;
        }
</style>


<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="card card-info  mt-3">
                <div class="card-header">
                    <h3 class="card-title">會員清單</h3>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table" id="userList">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>帳號</th>
                            <th>姓名</th>
                            <th>狀態</th>
                            <th>性別</th>
                            <th>信箱</th>
                            <th>累計點數</th>
                            <th>加入時間</th>

                        </tr>
                    </thead>
                    <tbody>
                        @*排序*@
                        @{int i = 0;}
                        @foreach (var user in Model.userList)
                        {
                            <tr>
                                <td>@{i += 1;}@i</td>

                                <td>
                                    <a href="@Url.Action("UserList","UserInfo",new { uid = user.uid })" class="btn btn-info btn-sm">
                                    <i class="fas fa-eye"></i>
                                    </a>
                                </td>

                                <th>@user.account</th>
                                <th>@user.name</th>

                                @if (user.status == "關閉")
                                {
                                    <th class="error text-danger">@user.status</th>
                                }
                                else if (user.status == "正常")
                                {
                                    <th class="error text-green">@user.status</th>
                                }
                                else
                                {
                                    <th class="error text-gray">@user.status</th>
                                }
                                <td>@user.sex</td>
                                <td>@user.email</td>
                                <td>@user.point</td>
                                <td>@user.creatdate</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            @*頁碼*@
            <!--<div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0">-->
            <!--	Here the JS Function Will Add the Rows -->
            <!--</ul>
            </div>-->


        </div>
    </section>
</div>

<script src="~/adminlte/plugins/jquery/jquery.js"></script>
@*<script type="text/javascript">

        $(function () {

            //將要執行頁碼的TableID放入呼叫func
            getPagination('#userList');

            //判斷Table列數產生頁碼
            function getPagination(table) {

                //將class:pagination內的html初始
                $('.pagination').html('');
                //一頁最多顯示的列數
                var maxRows = 2;
                //所有資料列數
                var totalRows = $(table + ' tbody tr').length;

                //資料列數變數初始
                var trnum = 0;
                //Table跑每一列資料<tr>
                $(table + ' tr:gt(0)').each(function () {

                    trnum++;

                    //如果超過設定的顯示列數
                    if (trnum > maxRows) {

                        $(this).hide();

                    } else {

                        if (trnum <= maxRows) { $(this).show(); }
                    }

                });


                //如總列數超過設定顯示列數
                if (totalRows > maxRows) {

                    //  總頁數 = ( 總列數 除 顯示列數 ) 無條件進位 。
                    var pagenum = Math.ceil(totalRows / maxRows);

                    //從1開始至總頁數
                    for (var i = 1; i <= pagenum;) {

                        //在class:pagination內加入<li>頁碼
                        $('.pagination').append('<li class="page-item" data-page="' + i + '">\
                                                <span>'+ i++ + '<span class="sr-only">(current)</span></span>\
                                                </li>').show();
                    }

                }

                //頁碼的點擊事件
                $('.page-item').on('click', function (e) {

                    //阻止表單的提交
                    e.preventDefault();
                    //取得頁碼
                    var pageNum = $(this).attr('data-page');

                    //$('.pagination li').removeClass('active');	// remove active class from all li
                    //$(this).addClass('active');					// add active class to the clicked

                    //資料列數變數初始
                    var trIndex = 0;
                    //Table跑每一列資料<tr>
                    $(table + ' tr:gt(0)').each(function () {

                        trIndex++;

                        //判斷 列數是否超過 最大顯示列數*頁碼   或   小於等於 最大顯示列數*頁碼-最大顯示列數
                        //ex. (最大顯示列數為10) 點擊第二頁時 若資料列數 > 20 或 <= 10 的資料都被隱藏 ==> 顯示11-20的資料
                        if (trIndex > (maxRows * pageNum) || trIndex <= ((maxRows * pageNum) - maxRows)) {
                            $(this).hide();
                        } else {
                            $(this).show();
                        }
                    });
                });
                //頁碼的點擊事件-END


            }
        });

    </script>*@

YodaCodingForumBack/Views/UserInfo/Search.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor hca
@model YodaCodingForumBack.Models.SearchClass
@{
    ViewData["Title"] = "會員搜尋";
}
<div class="content-wrapper">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">會員清單</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>帳號</th>
                        <th>姓名</th>
                        <th>狀態</th>
                        <th>性別</th>
                        <th>信箱</th>
                        <th>累計點數</th>
                        <th>加入時間</th>

                    </tr>
                </thead>
                <tbody>
                    @*排序*@
                    @{int i = 0;}
                    @foreach (var user in Model.userList)
                    {
                        <tr>
                            <td>@{i += 1;}@i</td>
                            <th>@user.account</th>
                            <th>@user.name</th>

                            @if (user.status == "關閉")
                            {
                                <th class="error text-danger">@user.status</th>
                            }
                            else if (user.status == "正常")
                            {
                                <th class="error text-green">@user.status</th>
                            }
                            else
                            {
                                <th class="error text-gray">@user.status</th>
                            }
                            <td>@user.sex</td>
                            <td>@user.email</td>
                            <td>@user.point</td>
                            <td>@user.creatdate</td>

                            <td class="text-right py-0 align-middle">
                                <div class="btn-group btn-group-sm">
                                    <a href="@Url.Action("UserList","UserInfo",new { uid = user.uid })" class="btn btn-info"><i class="fas fa-eye"></i></a>
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
</div>